apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'registry-1.docker.io/nadav0176'
    chart: payment-app
    targetRevision: 0.1.0
    helm:
      valueFiles:
        - $values/ConfigFiles/Helm/payment-app/values.yaml
      version: v3
  - repoURL: 'https://gitlab.com/sela-tracks/1099/students/nadavb/application/payment_app.git'
    targetRevision: main
    ref: values
  destination:
    namespace: application 
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      