apiVersion: v1
kind: Service
metadata:
  name: payment-app-service
spec:
  selector:
    app: payment-app
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
        - name: payment-app
          image: nadav0176/payment_app:0.9
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: connection-secret
                  key: MYSQL_DATABASE
            - name: DB_HOST
              value: mysql.database.svc.cluster.local
            - name: DB_PORT
              value: 3306  
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: connection-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: connection-secret
                  key: MYSQL_PASSWORD 