apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2 # Base64 encoded value of "123456"
  MYSQL_DATABASE: cGF5bWFudF9hcHA= # Base64 encoded value of "paymant_app"
  MYSQL_USER: bmFkYXY= # Base64 encoded value of "nadav"
  MYSQL_PASSWORD: MTIzNDU2 # Base64 encoded value of "123456"